# Generated by Django 5.2.16 on 2026-07-14 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الخصم')),
                ('discount', models.PositiveIntegerField(verbose_name='نسبة الخصم %')),
                ('active', models.BooleanField(default=True, verbose_name='نشط / متوفر للاستخدام')),
            ],
            options={
                'verbose_name': 'كوبون خصم',
                'verbose_name_plural': 'كوبونات الخصم',
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المحافظة')),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تكلفة الشحن (جنيه)')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات وتكاليف الشحن',
            },
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='الحد الأدنى للشحن المجاني (جنيه)')),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='مبلغ الخصم المطبق'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة شحن الطلب'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر بعد الخصم (اختياري)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='المدينة / المنطقة'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coupon', verbose_name='الكوبون المستخدم'),
        ),
        migrations.AddField(
            model_name='order',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.governorate', verbose_name='المحافظة'),
        ),
    ]
