# Generated by Django 5.2.16 on 2026-07-16 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_coupon_governorate_storesetting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('rating', models.PositiveIntegerField(choices=[(1, '★☆☆☆☆ (1/5)'), (2, '★★☆☆☆ (2/5)'), (3, '★★★☆☆ (3/5)'), (4, '★★★★☆ (4/5)'), (5, '★★★★★ (5/5)')], default=5, verbose_name='التقييم بالنجوم')),
                ('comment', models.TextField(verbose_name='التعليق والملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم منتج',
                'verbose_name_plural': 'تقييمات المنتجات',
                'ordering': ('-created_at',),
            },
        ),
    ]
