# Generated by Django 5.2.16 on 2026-07-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='نص الإعلان')),
                ('active', models.BooleanField(default=True, verbose_name='نشط / معروض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'إعلانات شريط الإعلانات',
                'ordering': ('-created_at',),
            },
        ),
    ]
